achievement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views
from dashboard import views as user_views
from django.conf import settings
from django.conf.urls.static import static

# Django admin header configuration
admin.site.site_header="Faculty Portal"
admin.site.site_title="Faculty Portal"
admin.site.index_title="Admin for Faculty Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include('dashboard.urls')),
    path('',include('publications.urls')),
    path('',authentication_views.LoginView.as_view(template_name='dashboard/login.html'),name='login'),
    
    path('logout/',authentication_views.LogoutView.as_view(template_name='dashboard/logout.html'),name='logout'),

    # reset password urls
    path('reset_password/', authentication_views.PasswordResetView.as_view(template_name='dashboard/password_reset.html'), name="reset_password"),
    path('reset_password_sent/', authentication_views.PasswordResetDoneView.as_view(template_name='dashboard/password_reset_sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', authentication_views.PasswordResetConfirmView.as_view(template_name='dashboard/password_reset_form.html'), name="password_reset_confirm"),
    path('reset_password_complete/', authentication_views.PasswordResetCompleteView.as_view(template_name='dashboard/password_reset_done.html'), name="password_reset_complete"),
    
    path('password_change/',authentication_views.PasswordChangeView.as_view(template_name='dashboard/password_change.html'), name='password_change'),
    path('password_change_done/',authentication_views.PasswordChangeDoneView.as_view(template_name='dashboard/password_change_done.html'), name='password_change_done'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name='dashboard'
urlpatterns = [
    path('', views.main, name='main'),
    path('display/',views.display,name='display'),
    path('add/',views.add,name='add'),
    path('stat/',views.statistic,name='statistic'),
    path('display_all/',views.displayAll,name='display_all'),
    path('update/<int:id>/',views.update, name='update'),
    path('data/',views.data,name='data'),
    path('delete/<int:id>/',views.delete_data, name="delete_data"), 
    path('displayall_hod/',views.displayAll_hod,name='displayall_hod'),
    path('stat_hod/',views.statistic_hod,name='statistic_hod'),
    path('upload_ach/',views.upload_ach,name='upload_ach'),
    path('display_ach/',views.display_ach, name="display_ach"),
    path('delete_ach/<int:id>/',views.delete_ach, name="delete_ach"),

    path('statoverall/',views.statistic_overall,name='statistic_overall'),
    path('myprofile/',views.addmyprofile,name='addmyprofile'),
    
    path('viewprofile/',views.viewprofile,name='viewprofile'),

    path('viewmyprofile/',views.viewmyprofile,name='viewmyprofile'),

    path('updatemyprofile/<int:id>/',views.updatemyprofile, name='updatemyprofile'),

    path('excel',views.excel, name="excel"),  
    path('pdf',views.pdf, name="pdf"),

    path('pdf_indi',views.pdf_indi, name="pdf_indi"),
    path('excel_indi',views.excel_indi, name="excel_indi"), 

    path('addcompe/',views.addcompe,name='addcompe'),
    path('displaycompe/',views.displaycompe,name='displaycompe'),
    path('displaycompeh/',views.displaycompeh,name='displaycompeh'),

    path('addresearchgrant/',views.addresearchgrant,name='addresearchgrant'),
    path('displayresearchgrant/',views.displayresearchgrant,name='displayresearchgrant'),
    path('displayrghod/',views.displayrghod,name='displayrghod'),

    path('addacademicrr/',views.addacademicrr,name='addacademicrr'),
    path('displayacademicrr/',views.displayacademicrr,name='displayacademicrr'),
    path('displayacademicrhod/',views.displayacademicrhod,name='displayacademicrhod'),

    path('addpubaward/',views.addpubaward,name='addpubaward'),
    path('displaypubaward/',views.displaypubaward,name='displaypubaward'),
    path('displaypubawardhod/',views.displaypubawardhod,name='displaypubawardhod'),

    path('addconsultancy/',views.addconsultancy,name='addconsultancy'),
    path('displayconsultancy/',views.displayconsultancy,name='displayconsultancy'),
    path('displaypubawardhod/',views.displaypubawardhod,name='displaypubawardhod'),

    path('addexpert/',views.addexpert,name='addexpert'),
    path('displayexpert/',views.displayexpert,name='displayexpert'),
    path('displayexperthod/',views.displayexperthod,name='displayexperthod'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

publications/urls.py
from django.urls import path
from .import views

app_name='publications'
urlpatterns = [
    
    path('pub_c/', views.pub_c, name='pubc'),
    path('pub_j/', views.pub_j, name="pubj"),
    path('bookchapter/', views.bookchapter, name="bookchapter"),
    path('book/', views.book, name="book"),
    path('patent/', views.patent, name="patent"),
    path('copyright/', views.copyright, name="copyright"),


    path('display_p/',views.display_p, name="displayp"),
    path('updatec/<int:id>/',views.updatec, name='updatec'),
    path('updatej/<int:id>/',views.updatej, name='updatej'),
    path('updatebc/<int:id>/',views.updatebc, name='updatebc'),
    path('updateb/<int:id>/',views.updateb, name='updateb'),
    path('updatep/<int:id>/',views.updatep, name='updatep'),
    path('updateco/<int:id>/',views.updateco, name='updateco'),
    path('statisticpub',views.statisticpub, name='statisticpub'),


    path('displayAllHod/',views.displayAllHod,name='displayAllHod'),
    path('statpub_hod/',views.statisticpub_hod,name='statisticpub_hod'),
    path('displayAllp/',views.displayAllp,name='displayAllp'),

    path('statoverallp/',views.statistic_overallp, name='statistic_overallp'),

    path('deletec/<int:id>/',views.deletec, name="deletec"), 
    path('deletej/<int:id>/',views.deletej, name="deletej"), 
    path('deletebc/<int:id>/',views.deletebc, name="deletebc"), 
    path('deleteb/<int:id>/',views.deleteb, name="deleteb"), 
    path('deletep/<int:id>/',views.deletep, name="deletep"), 
    path('deleteco/<int:id>/',views.deleteco, name="deleteco"), 

    path('pdfp',views.pdfp, name="pdfp"),
    
    
]

publications/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template import loader
from .models import Publication_C, Publication_J, BookChapter, Book, Patent, Copyright
from .forms import Publication_CForm,Publication_JForm, BookChapterForm, BookForm, PatentForm, CopyrightForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import io


import pdfkit
from django.template import loader
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
import xlwt


# Create your views here.

@login_required
def pub_c(request):
    if request.method=="POST":
        form = Publication_CForm(request.POST or None,request.FILES)
        if request.POST:
            val = request.POST.get('scopus', False)
            if val == "Yes":
                form.fields['scopus_value'].required = True
        if form.is_valid():
            instance= form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()  
            return redirect('dashboard:main')
    else:
        form = Publication_CForm()
    return render(request,'publications/pubc.html',{'form':form})


@login_required
def pub_j(request):
    if request.method=="POST":
        form = Publication_JForm(request.POST or None,request.FILES)
        if request.POST:
            val = request.POST.get('scopus', False)
            if val == "Yes":
                form.fields['scopus_value'].required = True
        if form.is_valid():
            instance=form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()
            return redirect('dashboard:main')
    else:
        form = Publication_JForm()
    return render(request,'publications/pubj.html',{'form':form})



@login_required
def bookchapter(request):
    if request.method=="POST":
        form = BookChapterForm(request.POST or None,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()
            return redirect('dashboard:main')
    else:
        form = BookChapterForm()
    return render(request,'publications/bookchapter.html',{'form':form})



@login_required
def book(request):
    if request.method=="POST":
        form = BookForm(request.POST or None,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()
            return redirect('dashboard:main')
    else:
        form = BookForm()
    return render(request,'publications/book.html',{'form':form})


@login_required
def patent(request):
    if request.method=="POST":
        form = PatentForm(request.POST or None,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()
            return redirect('dashboard:main')
    else:
        form = PatentForm()
    return render(request,'publications/patent.html',{'form':form})



@login_required
def copyright(request):
    if request.method=="POST":
        form = CopyrightForm(request.POST or None,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()
            return redirect('dashboard:main')
    else:
        form = CopyrightForm()
    return render(request,'publications/copyright.html',{'form':form})



@login_required
def display_p(request):
    con = Publication_C.objects.filter(faculty= request.user)
    jor = Publication_J.objects.filter(faculty=request.user)
    bookc = BookChapter.objects.filter(faculty=request.user)
    book = Book.objects.filter(faculty=request.user)
    patent = Patent.objects.filter(faculty=request.user)
    copy = Copyright.objects.filter(faculty=request.user)
    
    context ={
        'con':con,
        'jor':jor,
        'bookc':bookc,
        'book':book,
        'patent':patent,
        'copy':copy,

    }
    return render(request,'publications/displayp.html',context)


@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def displayAllHod(request):

    con = Publication_C.objects.filter(department=request.user.profile.dept).order_by('faculty')
    jor = Publication_J.objects.filter(department=request.user.profile.dept).order_by('faculty')
    bookc = BookChapter.objects.filter(department=request.user.profile.dept).order_by('faculty')
    book = Book.objects.filter(department=request.user.profile.dept).order_by('faculty')
    patent = Patent.objects.filter(department=request.user.profile.dept).order_by('faculty')
    copy = Copyright.objects.filter(department=request.user.profile.dept).order_by('faculty')
    
    context ={
        'con':con,
        'jor':jor,
        'bookc':bookc,
        'book':book,
        'patent':patent,
        'copy':copy,       
        
    }
    return render(request,'publications/displayAllHod.html',context)


@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def displayAllp(request):
    

    con = Publication_C.objects.all().order_by('faculty')
    jor = Publication_J.objects.all().order_by('faculty')
    bookc = BookChapter.objects.all().order_by('faculty')
    book = Book.objects.all().order_by('faculty')
    patent = Patent.objects.all().order_by('faculty')
    copy = Copyright.objects.all().order_by('faculty')

    
    
    context ={
        'con':con,
        'jor':jor,
        'bookc':bookc,
        'book':book,
        'patent':patent,
        'copy':copy,   
        
    }
    return render(request,'publications/displayAllp.html',context)


@login_required
def updatec(request,id):
    conu = Publication_C.objects.get(id=id)
    form = Publication_CForm(request.POST or None, request.FILES or None, instance=conu)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('publications:displayp')
    return render(request,'publications/pubc.html',{'form':form})


@login_required
def updatej(request,id):
    joru = Publication_J.objects.get(id=id)
    form = Publication_JForm(request.POST or None, request.FILES or None, instance=joru)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('publications:displayp')
    return render(request,'publications/pubj.html',{'form':form})


@login_required
def updatebc(request,id):
    bookcu = BookChapter.objects.get(id=id)
    form = BookChapterForm(request.POST or None, request.FILES or None, instance=bookcu)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('publications:displayp')
    return render(request,'publications/bookchapter.html',{'form':form})


@login_required
def updateb(request,id):
    booku = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES or None, instance=booku)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('publications:displayp')
    return render(request,'publications/book.html',{'form':form})


@login_required
def updatep(request,id):
    patentu = Patent.objects.get(id=id)
    form = PatentForm(request.POST or None, request.FILES or None, instance=patentu)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('publications:displayp')
    return render(request,'publications/patent.html',{'form':form})


@login_required
def updateco(request,id):
    copyu = Copyright.objects.get(id=id)
    form = CopyrightForm(request.POST or None, request.FILES or None, instance=copyu)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('publications:displayp')
    return render(request,'publications/copyright.html',{'form':form})



@login_required
def statisticpub_hod(request):
    if request.POST:
        years = request.POST.get('years', False)       
    else:
        years="2020-2021"
                  
    pubcons={}
    pubjors={}
    bookchaps={} 
    bookks={}
    patentts={}
    copyrightts={}
   
    all_user = User.objects.all().exclude(is_superuser=True).exclude(username="admin")
    
    for user in all_user:
       
        u = user
        pubcon = Publication_C.objects.filter(faculty=user,academic_years=years).count()
        pubcons.update({u:pubcon})
        pubjor = Publication_J.objects.filter(faculty=user,academic_years=years).count()
        pubjors.update({u:pubjor})

        bookchap = BookChapter.objects.filter(faculty=user,academic_years=years).count()
        bookchaps.update({u:bookchap})

        bookk = Book.objects.filter(faculty=user,academic_years=years).count()
        bookks.update({u:bookk})

        patentt = Patent.objects.filter(faculty=user,academic_years=years).count()
        patentts.update({u:patentt})

        copyrightt = Copyright.objects.filter(faculty=user,academic_years=years).count()
        copyrightts.update({u:copyrightt})
        
    
    context ={
        'all_user':all_user,
        'u':u,
        'pubcons':pubcons,
        'pubjors':pubjors,
        'bookchaps':bookchaps,
        'bookks':bookks,
        'patentts':patentts,
        'copyrightts':copyrightts,
        
    } 
    return render(request,'publications/statisticpub_hod.html',context)


@login_required
def statisticpub(request):
    if request.POST:

publications/templates/publications/book.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Book {% endblock %} </title> 
    {% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/add.css' %}">
        
    {% endblock %}
    
    

</head> 
<body>
{% block body %}
<div class="table-responsive">
<form method="POST" enctype="multipart/form-data">
{% csrf_token %} 
<center><h5 class="bg-warning">Book Form</h5></center>
<table class="table table-hover">
    {% for form in form %}
    <tr>
        <td width="20%"><h4>{{ form.label }}</h4></td>
        <td><h5>{{ form }}</h5></td>
            
    </tr>    
    {% endfor %}
</table>

<center><button class="btn btn-primary border btn-outline-dark btn-lg" type ="Submit">Save</button></center>

</form>
</div>
{% endblock %}

</body>
</html>

publications/templates/publications/bookchapter.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Book Chapter {% endblock %} </title> 
    {% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/add.css' %}">
        
    {% endblock %}
    
    

</head> 
<body>
{% block body %}
<div class="table-responsive">
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<center><h5 class="bg-warning">Book Chapter Form</h5></center> 
<table class="table table-hover">
    {% for form in form %}
    <tr>
        <td width="20%"><h4>{{ form.label }}</h4></td>
        <td><h5>{{ form }}</h5></td>
            
    </tr>    
    {% endfor %}
</table>

<center><button class="btn btn-primary border btn-outline-dark btn-lg" type ="Submit">Save</button></center>

</form>
</div>
{% endblock %}

</body>
</html>

publications/templates/publications/delete.html
{% load static %}
<!DOCTYPE html>
<head>
<title> Logout </title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="{% static 'dashboard/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/logout.css' %}">
</head> 
<body>
<div class="container bg-primary">

<form method="POST">
{% csrf_token %}
<h2> Are u sure u want to delete? </h2>
<button class="btn btn-danger btn-lg" type="submit">Confirm</button>
<button class="btn btn-success btn-lg" onclick="window.history.back();" type="button">Cancel</button>
</form>

</div>

</body>
</html>

publications/templates/publications/displayp.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Display {% endblock %}</title>
    
    {% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/tablepub.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/logic.css' %}">
    {% endblock %}

</head> 
<body>
{% block body %}
<center>
<label><h5>Select the Publication Type:</label>
<select id="dynamictable">
    <option value="" selected>-------</option>
    <option value="conference">Conference Details</option>
    <option value="journal">Journal Details</option>
    <option value="bookchapter">Book Chapter Details</option>
    <option value="book">Book Details</option>
    <option value="patent">Patent Details</option>
    <option value="copyright">Copyright Details</option>
</select>
</center>
<div id="mytable">
    <div id="conference">
        <h5 class="bg-warning">Conference Details</h5>
        <table class="table table-hover ">
            <tr>       
                <th> Academic Year </th>
                <th> Title </th>
                <th> Conference Name </th>
                <th> Author Names </th>
                <th> Publication Year </th>
                <th> DOI </th>
                <th> ISSN </th>
                <th> Publisher </th>
                <th> Scopus Index</th>
                <th> View Certificate</th>
                <th> Update </th>
                <th> Delete </th>
                             
            </tr>
        
            {% for con in con %}
            <tr>               
                <td> {{ con.academic_years }} </td>
                <td> {{ con.title }} </td>
                <td> {{ con.cname }} </td>
                <td> {{ con.authname }} </td>
                <td> {{ con.pubyears }} </td>
                <td> {{ con.doi }} </td>
                <td> {{ con.issn }} </td>
                <td> {{ con.publisher }} </td>
                {% if con.scopus == "Yes" %}
                    <td> {{ con.scopus }} - {{ con.scopus_value}} </td>
                {% else %}
                    <td> {{ con.scopus }} </td>
                {% endif %}
                {% if con.certificate.url is not null %}
                    <td><a href="{{ con.certificate.url }}" target="_blank">View</a></td>
                {% else %}
                <td class="table-danger">No Data</td>        
                {% endif %}                
                <td><a href="{% url 'publications:updatec' con.id %}"> Update </a></td>  
                <td class="table-danger"><b><a href="{% url 'publications:deletec' con.id %}"> Delete </a></b></td>      
                
            </tr>        
            {% endfor %}
        </table>

    </div>
    <div id="journal">
        <h5 class="bg-warning">Journal Details</h5>
        <table class="table table-hover ">
        <tr>
            <th> Academic Year </th>
            <th> Title </th>
            <th> Journal Name </th>            
            <th> Page Number </th>
            <th> Publication Years </th>
            <th> DOI </th>
            <th> Publisher </th>
            <th> Scopus Index</th>
            <th> View Certificate</th>
            <th> Update </th>
            <th> Delete </th>
                    
        </tr>

        {% for jor in jor %}
        <tr>
            <td> {{ jor.academic_years }} </td>
            <td> {{ jor.title }} </td>
            <td> {{ jor.jname }} </td>            
            <td> {{ jor.pageno }} </td>
            <td> {{ jor.pubyears }} </td>
            <td> {{ jor.doi }} </td>
            <td> {{ jor.publisher }} </td>
            {% if  jor.scopus == "Yes" %}
                <td> {{  jor.scopus }} - {{  jor.scopus_value}} </td>
            {% else %}
                <td> {{  jor.scopus }} </td>
            {% endif %}
            {% if jor.certificate.url is not null %}
                <td><a href="{{ jor.certificate.url }}" target="_blank">View</a></td>
            {% else %}
            <td class="table-danger">No Data</td>
            {% endif %}            
            <td><a href="{% url 'publications:updatej' jor.id %}"> Update </a></td>
            <td class="table-danger"><b><a href="{% url 'publications:deletej' jor.id %}"> Delete </a></b></td>
                  
        </tr>
        {% endfor %}
        </table>
    </div>

    <div id="bookchapter">
        <h5 class="bg-warning">Book Chapter Details</h5>
        <table class="table table-hover ">
        <tr>
            <th> Academic Year </th>
            <th> Chapter Title </th>
            <th> Book Name </th>
            <th> Editors Name </th>
            <th> Volume Number </th>
            <th> Issue Number </th>
            <th> Page(s) </th>
            <th> Year of publication </th>
            <th> DOI </th>
            <th> Publisher </th>
            <th> View Certificate</th>
            <th> Update </th>
            <th> Delete </th>
                   
        </tr>

        {% for bookc in bookc %}
        <tr>      
            <td> {{ bookc.academic_years }} </td>
            <td> {{ bookc.chapter_title }} </td>
            <td> {{ bookc.book_name }} </td>
            <td> {{ bookc.editors }} </td>
            <td> {{ bookc.volno }} </td>
            <td> {{ bookc.issueno }} </td>
            <td> {{ bookc.pageno }} </td>
            <td> {{ bookc.pubyears }} </td>
            <td> {{ bookc.doi }} </td>
            <td> {{ bookc.publisher }} </td>
            {% if bookc.certificate.url is not null %}
                <td><a href="{{ bookc.certificate.url }}" target="_blank">View</a></td>
            {% else %}
                <td class="table-danger">No Data</td>
            {% endif %}            
            <td><a href="{% url 'publications:updatebc' bookc.id %}"> Update </a></td>
            <td class="table-danger"><b><a href="{% url 'publications:deletebc' bookc.id %}"> Delete </a></b></td>
            
        </tr>
        {% endfor %}    
        </table>
    </div>
    <div id="book">
        <h5 class="bg-warning">Book Details</h5>
        <table class="table table-hover ">
        <tr>
            <th> Academic Year </th>
            <th> Book Name </th>
            <th> Name of Authors </th>
            <th> Publisher </th>
            <th> ISBN </th>
            <th> DOI </th>
            <th> Year of publication </th>
            <th> View Certificate</th>
            <th> Update </th>
            <th> Delete </th>
            
        </tr>

        {% for book in book %}
        <tr>
            <td> {{ book.academic_years }} </td>
            <td> {{ book.book_name }} </td>
            <td> {{ book.authname }} </td>
            <td> {{ book.publisher }} </td>
            <td> {{ book.isbn }} </td>
            <td> {{ book.doi }} </td>
            <td> {{ book.pubyears }} </td>
            {% if book.certificate.url is not null %}
                <td><a href="{{ book.certificate.url }}" target="_blank">View</a></td>
            {% else %}
                <td class="table-danger">No Data</td>
            {% endif %}
            <td><a href="{% url 'publications:updateb' book.id %}"> Update </a></td>
            <td class="table-danger"><b><a href="{% url 'publications:deleteb' book.id %}"> Delete </a></b></td>
                 
        </tr>
        {% endfor %}    
        </table>
    </div>

    <div id="patent">
        <h5 class="bg-warning">Patent Details</h5>
        <table class="table table-hover ">
        <tr>
            <th> Academic Year </th>
            <th> Patent Title </th>
            <th> Patent type </th>
            <th> Patent Number </th>
            <th> Grant Year </th>
            <th> Grant Term </th>
            <th> View Certificate</th>
            <th> Update </th>
            <th> Delete </th>
            
        </tr>

        {% for patent in patent %}
        <tr>
            <td> {{ patent.academic_years }} </td>
            <td> {{ patent.title }} </td>
            <td> {{ patent.ptype }} </td>
            <td> {{ patent.patentno }} </td>
            <td> {{ patent.grantyears }} </td>
            <td> {{ patent.term }} </td>
            {% if patent.certificate.url is not null %}
                <td><a href="{{ patent.certificate.url }}" target="_blank">View</a></td>
            {% else %}
                <td class="table-danger">No Data</td>
            {% endif %}
            <td><a href="{% url 'publications:updatep' patent.id %}"> Update </a></td>
            <td class="table-danger"><b><a href="{% url 'publications:deletep' patent.id %}"> Delete </a></b></td>
             
        </tr>
        {% endfor %}
        </table>
    </div>

    <div id="copyright">
        <h5 class="bg-warning">Copyright Details</h5>
        <table class="table table-hover ">
        <tr>
            <th> Academic Year </th>
            <th> Copyright Title </th>
            <th> Granted On </th>
            <th> Registeration Number </th>
            <th> View Certificate </th>
            <th> Country of Grant </th>
            <th> Update </th>
            <th> Delete </th>
                
        </tr>

        {% for copy in copy %}
        <tr>
            <td> {{ copy.academic_years }} </td>
            <td> {{ copy.title }} </td>
            <td> {{ copy.grantdate }} </td>
            <td> {{ copy.regno }} </td>
            <td> {{ copy.grantcountry }} </td>
            {% if copy.certificate.url is not null %}
                <td><a href="{{ copy.certificate.url }}" target="_blank">View</a></td>
            {% else %}
                <td class="table-danger">No Data</td>
            {% endif %}
            <td><a href="{% url 'publications:updateco' copy.id %}"> Update </a></td>
            <td class="table-danger"><b><a href="{% url 'publications:deleteco' copy.id %}"> Delete </a></b></td>
             
        </tr>
        {% endfor %}
        </table>
    </div>
</div>

{% block js_block %}
<script type = "text/javascript">
jQuery(function () 
{
    $('#dynamictable').change(function () 
    {
        $('#mytable > div').css('display', 'none');
        if (this.value) 
        {
            $('#' + this.value).css('display', 'block');
        }
    }).change()
})
</script>

{% endblock %}

{% endblock %}


</body>
</html>