achievement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views
from dashboard import views as user_views
from django.conf import settings
from django.conf.urls.static import static

# Django admin header configuration
admin.site.site_header="Faculty Portal"
admin.site.site_title="Faculty Portal"
admin.site.index_title="Admin for Faculty Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include('dashboard.urls')),
    path('',include('publications.urls')),
    path('',authentication_views.LoginView.as_view(template_name='dashboard/login.html'),name='login'),
    
    path('logout/',authentication_views.LogoutView.as_view(template_name='dashboard/logout.html'),name='logout'),

    # reset password urls
    path('reset_password/', authentication_views.PasswordResetView.as_view(template_name='dashboard/password_reset.html'), name="reset_password"),
    path('reset_password_sent/', authentication_views.PasswordResetDoneView.as_view(template_name='dashboard/password_reset_sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', authentication_views.PasswordResetConfirmView.as_view(template_name='dashboard/password_reset_form.html'), name="password_reset_confirm"),
    path('reset_password_complete/', authentication_views.PasswordResetCompleteView.as_view(template_name='dashboard/password_reset_done.html'), name="password_reset_complete"),
    
    path('password_change/',authentication_views.PasswordChangeView.as_view(template_name='dashboard/password_change.html'), name='password_change'),
    path('password_change_done/',authentication_views.PasswordChangeDoneView.as_view(template_name='dashboard/password_change_done.html'), name='password_change_done'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name='dashboard'
urlpatterns = [
    path('', views.main, name='main'),
    path('display/',views.display,name='display'),
    path('add/',views.add,name='add'),
    path('stat/',views.statistic,name='statistic'),
    path('display_all/',views.displayAll,name='display_all'),
    path('update/<int:id>/',views.update, name='update'),
    path('data/',views.data,name='data'),
    path('delete/<int:id>/',views.delete_data, name="delete_data"), 
    path('displayall_hod/',views.displayAll_hod,name='displayall_hod'),
    path('stat_hod/',views.statistic_hod,name='statistic_hod'),
    path('upload_ach/',views.upload_ach,name='upload_ach'),
    path('display_ach/',views.display_ach, name="display_ach"),
    path('delete_ach/<int:id>/',views.delete_ach, name="delete_ach"),

    path('statoverall/',views.statistic_overall,name='statistic_overall'),
    path('myprofile/',views.addmyprofile,name='addmyprofile'),
    
    path('viewprofile/',views.viewprofile,name='viewprofile'),

    path('viewmyprofile/',views.viewmyprofile,name='viewmyprofile'),

    path('updatemyprofile/<int:id>/',views.updatemyprofile, name='updatemyprofile'),

    path('excel',views.excel, name="excel"),  
    path('pdf',views.pdf, name="pdf"),

    path('pdf_indi',views.pdf_indi, name="pdf_indi"),
    path('excel_indi',views.excel_indi, name="excel_indi"), 

    path('addcompe/',views.addcompe,name='addcompe'),
    path('displaycompe/',views.displaycompe,name='displaycompe'),
    path('displaycompeh/',views.displaycompeh,name='displaycompeh'),

    path('addresearchgrant/',views.addresearchgrant,name='addresearchgrant'),
    path('displayresearchgrant/',views.displayresearchgrant,name='displayresearchgrant'),
    path('displayrghod/',views.displayrghod,name='displayrghod'),

    path('addacademicrr/',views.addacademicrr,name='addacademicrr'),
    path('displayacademicrr/',views.displayacademicrr,name='displayacademicrr'),
    path('displayacademicrhod/',views.displayacademicrhod,name='displayacademicrhod'),

    path('addpubaward/',views.addpubaward,name='addpubaward'),
    path('displaypubaward/',views.displaypubaward,name='displaypubaward'),
    path('displaypubawardhod/',views.displaypubawardhod,name='displaypubawardhod'),

    path('addconsultancy/',views.addconsultancy,name='addconsultancy'),
    path('displayconsultancy/',views.displayconsultancy,name='displayconsultancy'),
    path('displaypubawardhod/',views.displaypubawardhod,name='displaypubawardhod'),

    path('addexpert/',views.addexpert,name='addexpert'),
    path('displayexpert/',views.displayexpert,name='displayexpert'),
    path('displayexperthod/',views.displayexperthod,name='displayexperthod'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User



class DateInput(forms.DateInput):
    input_type='date'

class DataForm(forms.ModelForm):
   
    class Meta:
        model = Details
        fields = ['academic_years', 'typeas', 'modes', 'events','others', 'topic', 'college_name', 'start_date', 'end_date','certificate']
        
        widgets = {
        'start_date': DateInput(),
        'end_date': DateInput(),
    }

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['sal','dept']

class MyProfileForm(forms.ModelForm):

    class Meta:
        model = MyProfile
        fields = ['photo','dob','designation', 'doj', 'edbe','edme','edphd','expty','exptm', 'exptm', 'expiy','expim','pan', 'panproof', 'aadhar','aadharproof', 'resume','apletter']

        widgets = {
        'dob': DateInput(),
        'doj': DateInput(),
    }

class Show_AchieveForm(forms.ModelForm):

    class Meta:
        model = Show_Achieve
        fields = ['image']

class ProjectCompForm(forms.ModelForm):

    class Meta:
        model = ProjectComp
        fields = ['academic_years','cotype','event_type', 'others','award', 'proof']

class ResearchGrantForm(forms.ModelForm):

    class Meta:
        model = ResearchGrant
        fields = ['academic_years','title','amount','authority','term']

class AcademicRRForm(forms.ModelForm):

    class Meta:
        model = AcademicRR
        fields = ['academic_years','syllabusset','details','proof']

class PublicationAwardForm(forms.ModelForm):

    class Meta:
        model = PublicationAward
        fields = ['academic_years','type_pub','title','proof']

class ConsultancyForm(forms.ModelForm):

    class Meta:
        model = Consultancy
        fields = ['academic_years','type_con','orgdet','prodet','start_date','end_date','proof']

        widgets = {
        'start_date': DateInput(),
        'end_date': DateInput(),
    }

class ExpertLectureForm(forms.ModelForm):

    class Meta:
        model = ExpertLecture
        fields = ['academic_years','typeas','resource_person','subject','topic','years','date','present','attendance','proof']

        widgets = {
        'date': DateInput(),
    }

dashboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from .filters import *
import pdfkit
from django.template import loader
import io
import datetime
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
import xlwt

#main page

@login_required
def main(request):
    lst = {}
    img = Show_Achieve.objects.all()
    all_user = User.objects.all()
    bday = MyProfile.objects.all()
    cmonth = datetime.date.today().month
    cday = datetime.date.today().day
 
    context ={
        'img':img,
        'cmonth':cmonth,
        'cday':cday, 
        'bday':bday,
        'all_user':all_user,      
    }
    return render(request,'dashboard/main.html',context)

@login_required
def upload_ach(request):
    if request.method == 'POST':
        form = Show_AchieveForm(request.POST or None,request.FILES)
        if form.is_valid():
            form.save()   
            return redirect('dashboard:main')
    else:
        form = Show_AchieveForm()
    return render(request,'dashboard/upload_ach.html',{'form':form})


#Form to add data
@login_required
def add(request):
    
    if request.method == 'POST':
        form = DataForm(request.POST or None,request.FILES)
        if request.POST:
            val = request.POST.get('events', False)
            if val == "Others":
                form.fields['others'].required = True
                
        if form.is_valid():  
            
            instance= form.save(commit=False)
            instance.faculty = request.user
            instance.department = request.user.profile.dept
            instance.save()  
            return redirect('dashboard:main')
    else:
        form = DataForm()
    return render(request,'dashboard/add_data.html',{'form':form})

@login_required
def addmyprofile(request):

    all_user = User.objects.all()
    if request.method == 'POST':
        form = MyProfileForm(request.POST or None,request.FILES)
        if MyProfile.objects.filter(faculty__in=all_user).exists():
            messages.error(request,"User Profile already exists")
        else:
            if form.is_valid():  
                
                instance= form.save(commit=False)
                instance.faculty = request.user
                instance.department = request.user.profile.dept
                instance.form_submitted = True
                instance.save()  
                return redirect('dashboard:main')
    else:
        form = MyProfileForm()

    context={
        'form':form,
            
    }
    return render(request,'dashboard/addmyprofile.html',context)

@login_required
def viewmyprofile(request):
    profile = MyProfile.objects.filter(faculty= request.user)
    context ={
        'profile':profile,

    }
    return render(request,'dashboard/viewmyprofile.html',context)

@login_required
def updatemyprofile(request,id):

    item = MyProfile.objects.get(id=id)
    form = MyProfileForm(request.POST or None,request.FILES or None, instance=item)
    if form.is_valid(): 
        edit = form.save(commit=False) 
        edit.save()
        return redirect('dashboard:viewmyprofile')
    return render(request,'dashboard/addmyprofile.html',{'form':form,'item':item})


#update value to form
@login_required
def update(request,id):
    item = Details.objects.get(id=id)
    form = DataForm(request.POST or None, request.FILES or None, instance=item)
    if form.is_valid():
        edit = form.save(commit=False)
        edit.save()
        return redirect('dashboard:display')
    return render(request,'dashboard/add_data.html',{'form':form})


#delete data from records
@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def delete_data(request,id):
    del_data = Details.objects.get(id=id)
    if request.method=='POST':
        del_data.delete()
        return redirect('dashboard:displayall_hod')
    return render(request,'dashboard/delete_data.html',{'del_data':del_data})


@login_required
def viewprofile(request):

    display  = MyProfile.objects.all()
    context ={
        'display':display,
       

    }
    return render(request,'dashboard/viewprofile.html',context)

#display individual data
@login_required
def display(request):
    listt = Details.objects.filter(faculty= request.user).order_by('-academic_years')
    myFilter2 = DetailsFilter_indi(request.GET,queryset=listt)
    listt = myFilter2.qs 
    context ={
        'listt':listt,
        'myFilter2':myFilter2,

    }
    return render(request,'dashboard/display.html',context)


#display all data by management
@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def displayAll(request):
    
    dis_all = Details.objects.all().order_by('faculty')
    myFilter = DetailsFilter(request.GET,queryset=dis_all)
    
    dis_all = myFilter.qs    
    context ={
        'dis_all':dis_all,
        'myFilter':myFilter,         
        
    }
    return render(request,'dashboard/displayAll.html',context)


#display data to download
@login_required
def data(request):
    data = Details.objects.all().order_by('faculty')

    context={
        'data':data,
    }
    return render(request,'dashboard/data.html',context)


@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def displayAll_hod(request):
    
    dis_all = Details.objects.filter(department=request.user.profile.dept).order_by('-academic_years','faculty')
    myFilter1 = DetailsFilter_hod(request.GET,queryset=dis_all)
    
    dis_all = myFilter1.qs    
    context ={
        'dis_all':dis_all,
        'myFilter1':myFilter1,         
        
    }    
    return render(request,'dashboard/displayAll_hod.html',context)
#all_user = Details.objects.filter(department=request.user.profile.dept)


@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def display_ach(request):
    dis_ach = Show_Achieve.objects.all()
    context ={
        'dis_ach':dis_ach,
                
        
    }
    return render(request,'dashboard/display_ach.html',context)

@login_required
#@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def delete_ach(request,id):
    del_ach = Show_Achieve.objects.get(id=id)
    if request.method=='POST':
        del_ach.delete()
        return redirect('dashboard:display_ach')
    return render(request,'dashboard/delete_ach.html',{'del_ach':del_ach})

#display statistics
@login_required
def statistic(request):
    if request.POST:
        years = request.POST.get('years', False)
        dep = request.POST.get('dep',False)
        
    else:
        years="2020-2021"
        dep="Civil"     
        
    sttps={}
    fdps={}
    webinars={}
    nptels={}
    udemys={}
    totals={}
    ongoings={}
    completeds={}
    rnds={}
    fops={}
    
    courseras={}
    others={}
        
   
    all_user = User.objects.all().exclude(is_superuser=True).exclude(username="admin")
 
    for user in all_user:
        u = user
        total = Details.objects.filter(faculty=user,academic_years=years).count()
        totals.update({u:total})
        sttp = Details.objects.filter(faculty=user,academic_years=years,events='STTP').count()
        sttps.update({u:sttp})
        fdp = Details.objects.filter(faculty=user,academic_years=years,events='FDP').count()
        fdps.update({u:fdp})
        webinar = Details.objects.filter(faculty=user,academic_years=years,events='Webinar').count()
        webinars.update({u:webinar})
        nptel = Details.objects.filter(faculty=user,academic_years=years,events='NPTEL').count()
        nptels.update({u:nptel})
        udemy = Details.objects.filter(faculty=user,academic_years=years,events='Udemy').count()
        udemys.update({u:udemy})
        rnd = Details.objects.filter(faculty=user,academic_years=years,events='R&D Sessions').count()
        rnds.update({u:rnd})

        fop = Details.objects.filter(faculty=user,academic_years=years,events='Faculty Orienation Program').count()
        fops.update({u:fop})

        #Coursera Course Counts
        coursera = Details.objects.filter(faculty=user,academic_years=years,events='Coursera').count()
        courseras.update({u:coursera})

        #End of count logic

        other = Details.objects.filter(faculty=user,academic_years=years,events='Others').count()
        others.update({u:other})

    
        ongoing = Details.objects.filter(faculty=user,academic_years=years,certificate="").count()
        ongoings.update({u:ongoing})
        completed = Details.objects.filter(faculty=user,academic_years=years).exclude(certificate="").count()
        completeds.update({u:completed})
    
    
    context ={
        'sttp':sttp,
        'all_user':all_user,
        'u':u,
        'sttps':sttps,
        'fdps':fdps,
        'webinars':webinars,
        'nptels':nptels,
        'udemys':udemys,
        'rnds':rnds,
        'totals':totals,
        'ongoings':ongoings,
        'completeds':completeds,
        'total':total,  
        'dep':dep,  
        'fops':fops, 

        'courseras':courseras,
        'others':others,       

    }  
    return render(request,'dashboard/statistics.html',context)

#display statistics to hods
@login_required
def statistic_hod(request):
    if request.POST:
        years = request.POST.get('years', False)        
    else:
        years="2020-2021"
                   
    sttps={}
    fdps={}
    webinars={}
    nptels={}
    udemys={}
    totals={}
    ongoings={}
    completeds={}
    rnds={}
    fops={}

    courseras={}
    others={}
 
    all_user = User.objects.all().exclude(is_superuser=True).exclude(username="admin")
    
    
    for user in all_user:
       
        u = user

dashboard/templates/dashboard/add_comp.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Project Competitions {% endblock %} </title> 
    {% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/add.css' %}">
        
    {% endblock %}
    
    

</head> 
<body>
{% block body %}
<div class="table-responsive">
<form method="POST" enctype="multipart/form-data">
{% csrf_token %} 
<center><h5 class="bg-warning">Project Competitions</h5></center>
<table class="table table-hover">
    {% for form in form %}
    <tr>
        <td width="20%"><h4>{{ form.label }}</h4></td>
        <td><h5>{{ form }}</h5></td>
            
    </tr>    
    {% endfor %}
</table>

<center><button class="btn btn-primary border btn-outline-dark btn-lg" type ="Submit">Save</button></center>

</form>
</div>

{% block js_block %}
<script src="{% static 'js/addcompe.js' %}"></script> 
{% endblock %}

{% endblock %}

</body>
</html>

dashboard/templates/dashboard/addmyprofile.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} My Profile {% endblock %} </title> 
    {% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/add.css' %}">
        
    {% endblock %}   
</head> 

<body>
{% block body %}
{% if messages %}
    
    <center><h5 class="alert alert-danger">User Profile already exists!</h5></center>
    
{% endif %}

<div class="table-responsive">
<form id="profile" method="POST" enctype="multipart/form-data">
{% csrf_token %} 
<center><h5 class="bg-warning">My Profile</h5></center>
<table class="table table-hover">
    {% for form in form %}
    <tr>
        <td width="30%"><h4>{{ form.label }}</h4></td>
        <td><h5>{{ form }}</h5></td>
            
    </tr>    
    {% endfor %}
</table>

<center><button class="btn btn-primary border btn-outline-dark btn-lg" type ="Submit" >Save</button></center>

</form>
</div>

</form>
</div>
{% endblock %}



</script>
</body>
</html>

dashboard/templates/dashboard/delete_data.html
{% load static %}
<!DOCTYPE html>
<head>
<title> Logout </title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="{% static 'dashboard/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/logout.css' %}">
</head> 
<body>
<div class="container bg-primary">

<form method="POST">
{% csrf_token %}
<h2> Are u sure u want to delete? </h2>
<button class="btn btn-danger btn-lg" type="submit">Confirm</button>
<button class="btn btn-success btn-lg" onclick="window.history.back();" type="button">Cancel</button>
</form>

</div>

</body>
</html>

dashboard/templates/dashboard/display_ach.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Display {% endblock %}</title>
    {% block stylesheet %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/tableach.css' %}">
    {% endblock %}

</head> 
<body>
    {% block body %}
<div class="container col">
<table class="table table-hover ">
    
    <tr>
        
        <th> Faculty Name </th>
        <th> Department </th>
        <th> Achievement Displayed on </th>
        <th> Delete </th>
        
    </tr>

    {% for dis_ach in dis_ach %}
    <tr>
        
        <td> {{ dis_ach.faculty_name }} </td>
        <td> {{ dis_ach.department }} </td>
        <td> {{ dis_ach.date_uploaded }} </td>
        <td class="table-danger"><b><a href="{% url 'dashboard:delete_ach' dis_ach.id %}"> Delete </a></b></td>
     
        
        
    </tr>

    {% endfor %}
</table>
        
</div>

{% endblock %}

</body>
</html>

dashboard/templates/dashboard/display_compe.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Display {% endblock %}</title>
    {% block stylesheet %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/tableach.css' %}">
    {% endblock %}

</head> 
<body>
{% block body %}

    
<div class="container col">
<table class="table table-hover ">
    
    <tr>
        
        <th> Academic Year </th>
        <th> Competition Type </th>
        <th> Event Type </th>
        <th> Awards Type </th>
        <th> Proof </th>
     
        
    </tr>

    {% for compe in compe %}
    <tr>
        
        <td> {{ compe.academic_years }} </td> 
        <td> {{ compe.cotype }} </td>

        {% if compe.event_type == "Others" %}
            <td> {{ compe.others }} </td>
        {% else %}
            <td> {{ compe.event_type }} </td>
        {% endif %}

        <td> {{ compe.award }} </td>
        {% if compe.proof.url is not null %}
            <td><a href="{{ compe.proof.url }}" target="_blank">View</a></td>
        {% endif %}
               
    </tr>

    {% endfor %}
</table>
        
</div>

{% endblock %}

</body>
</html>

dashboard/templates/dashboard/display_compehod.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Display {% endblock %}</title>
    {% block stylesheet %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/tableach.css' %}">
    {% endblock %}

</head> 
<body>
{% block body %}
<div class="container">
    <div class="row align-items-center">
        <div class="col">
            <form method="GET">
            {% csrf_token %} 
            <center>

            {{filtercomh.form}}
            </center>
        </div>
    </div>
</div>
<center><button class="btn btn-info" type="Submit">Search</button></center><br>
    
<div class="container col">
<table class="table table-hover ">
    
    <tr>
        
        <th> Academic Year </th>
        <th> Faculty Name </th>
        <th> Competition Type </th>
        <th> Event Type </th>
        <th> Awards Type </th>
        <th> Proof </th>
     
        
    </tr>

    {% for compeh in compeh %}
    <tr>
        
        <td> {{ compeh.academic_years }} </td> 
        <td> {{ compeh.faculty.first_name }} {{ compeh.faculty.last_name }} </td>
        <td> {{ compeh.cotype }} </td>

        {% if compeh.event_type == "Others" %}
            <td> {{ compeh.others }} </td>
        {% else %}
            <td> {{ compeh.event_type }} </td>
        {% endif %}

        <td> {{ compeh.award }} </td>
        {% if compeh.proof.url is not null %}
            <td><a href="{{ compeh.proof.url }}" target="_blank">View</a></td>
        {% endif %}
               
    </tr>

    {% endfor %}
</table>
        
</div>

{% endblock %}

</body>
</html>

dashboard/templates/dashboard/display_consulthod.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Display {% endblock %}</title>
    {% block stylesheet %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/tableach.css' %}">
    {% endblock %}

</head> 
<body>
    {% block body %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-11">
                <form method="GET">
                {% csrf_token %} 
                <h5>
                {{filterconh.form}}
                </h5>
            </div>
        </div>
    </div>
    <center><button class="btn btn-info" type="Submit">Search</button></center><br>
    
<div class="container col">
<table class="table table-hover ">
    
    <tr>
        
        <th> Academic Year </th>
        <th> Faculty Name </th>
        <th> Consultancy Type </th>
        <th> Organization Details </th>
        <th> Project Details </th>
        <th> Start Date </th>
        <th> End Date </th>
        <th> Duration </th>
        <th> Proof </th>      
    </tr>

    {% for conh in conh %}
    <tr>
        
        <td> {{ conh.academic_years }} </td> 
        <td> {{ conh.faculty.first_name }} {{ conh.faculty.last_name }} </td>
        <td> {{ conh.type_con }} </td> 
        <td> {{ conh.orgdet }} </td> 
        <td> {{ conh.prodet }} </td> 
        <td> {{ conh.start_date }} </td> 
        <td> {{ conh.end_date }} </td> 
        <td> {{ conh.durations }} </td>   
        {% if conh.proof.url is not null %}
            <td><a href="{{ conh.proof.url }}" target="_blank">View</a></td>
        {% endif %}     
        
    </tr>

    {% endfor %}
</table>
        
</div>

{% endblock %}

</body>
</html>

dashboard/templates/dashboard/display_expert.html
{% extends 'dashboard/basenav.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %} Display {% endblock %}</title>
    {% block stylesheet %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/tableach.css' %}">
    {% endblock %}

</head> 
<body>
{% block body %}
 
    
<div class="container col">
<table class="table table-hover ">
    
    <tr>
        
        <th> Academic Year </th>
        <th> Type </th>
        <th> Name of Resource Person </th>
        <th> Subject Name </th>       
        <th> Topic </th>
        <th> Year </th>
        <th> Date of Expert Lecture </th>
        <th> Total Students Present </th>
        <th> Attendance Record (PDF Only) </th>
        <th> Proof </th>        
    </tr>

    {% for expert in expert %}
    <tr>
        
        <td> {{ expert.academic_years }} </td>
        <td> {{ expert.typeas }} </td>
        <td> {{ expert.resource_person }} </td>
        <td> {{ expert.subject }} </td>
        <td> {{ expert.topic }} </td>
        <td> {{ expert.years }} </td>
        <td> {{ expert.date }} </td>
        <td> {{ expert.present }} </td> 
               
        {% if expert.attendance.url is not null %}
            <td><a href="{{ expert.attendance.url }}" target="_blank">View</a></td>
        {% endif %}

        {% if expert.proof.url is not null %}
            <td><a href="{{ expert.proof.url }}" target="_blank">View</a></td>
        {% endif %}
         
        
    </tr>

    {% endfor %}
</table>
        
</div>

{% endblock %}

</body>
</html>